version: '3.7'
services:
  client:
    build:
      context: "./client"
      dockerfile: "./Dockerfile"
    container_name: "client"
    volumes:
      - "./client:/usr/app"
    ports:
      - "3000:3000"

  server:
    build: 
      context: "./server"
      dockerfile: "./Dockerfile"
    container_name: server
    volumes:
      - "./server:/usr/app"
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "testdatabase"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "test123"
    volumes:
      - .:/docker
    ports:
    - "5432:5432"
  
volumes:
  mongodb_data:
