version: '3.7'
services:
  mongo:
    image: mongo.4.4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
    - '27017:27017'
    volumes:
    - ./mongo_data:/data/db
    
  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - '15672:15672'
    - '5672:5672'
    
  volumes:
    mongodb_data:

